insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio Profesional de musica Francisco Escudero');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio Rimsky-Korsakov');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio de San Petersburgo');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio de Petrogrado');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio de Leningrado');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio Nacional Superior de Música y Danza de París');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio Nacional De Musica Juan Jose Landaeta');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Academia Nacional de Santa Cecilia');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Accademia Musicale Chigiana');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Conservatorio de San Pietro a Maiella');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'C . P. M. “Adolfo Salazar”');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'C . P. M. “Amaniel”');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'C . P. M.  de Arturo Soria');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'C . P. M.  “Joaquín Turina”');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'C . P. M.  “Victoria de los Ángeles”');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'C . P. M.  de Alcalá de Henares');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Hochschule für Musik Augsburg');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Hochschule für "Hans Eisler" Musik');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Universität der Künste Berlin');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Hochschule für Musik Detmold');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Escuela de Música Eastman');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Instituto Peabody');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Instituto de Música Curtis');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Escuela Juilliard');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Brooklyn-Queens Conservatory of Music');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Universidad de Columbia?');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Manhattan College?');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Vassar College');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Universidad Estatal de California?');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Universidad Catolica Andres Bello');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Universidad Central de Venezuela');
insert into INSTITUCION values(	SEQINSTITUCION.NEXTVAL	,'Universidad Catolica de Chile');