insert into VOZ values (	seqVoz.nextval	,	'soprano'	,	'aguda'	,	null	);
insert into VOZ values (	seqVoz.nextval	,	'mezzosoprano'	,	null	,	null	);
insert into VOZ values (	seqVoz.nextval	,	'contralto'	,	'grave'	,	null	);
insert into VOZ values (	seqVoz.nextval	,	'tenor'	,	'aguda'	,	null	);
insert into VOZ values (	seqVoz.nextval	,	'baritono'	,	null	,	null	);
insert into VOZ values (	seqVoz.nextval	,	'bajo'	,	'grave'	,	null	);
insert into VOZ values (	seqVoz.nextval	,	'ligera'	,	null	,	1	);
insert into VOZ values (	seqVoz.nextval	,	'lirica'	,	null	,	1	);
insert into VOZ values (	seqVoz.nextval	,	'dramatica'	,	null	,	1	);
insert into VOZ values (	seqVoz.nextval	,	'mezzo ligera'	,	null	,	2	);
insert into VOZ values (	seqVoz.nextval	,	'mezzo dramatica'	,	null	,	2	);
insert into VOZ values (	seqVoz.nextval	,	'ligero'	,	null	,	4	);
insert into VOZ values (	seqVoz.nextval	,	'lirico'	,	null	,	4	);
insert into VOZ values (	seqVoz.nextval	,	'dramatico'	,	null	,	4	);
insert into VOZ values (	seqVoz.nextval	,	'ligero'	,	null	,	5	);
insert into VOZ values (	seqVoz.nextval	,	'cantante'	,	null	,	5	);
insert into VOZ values (	seqVoz.nextval	,	'bajo'	,	null	,	5	);
insert into VOZ values (	seqVoz.nextval	,	'cantante'	,	null	,	6	);
insert into VOZ values (	seqVoz.nextval	,	'profundo'	,	null	,	6	);