insert into PERSONAJE values(	1	,	'Gioconda'	,	'cantante de baladas'	,	empty_blob()	,	1	,	9	,	5	);
insert into PERSONAJE values(	2	,	'La Cieca'	,	'su madre ciega'	,	empty_blob()	,	1	,	3	,	5	);
insert into PERSONAJE values(	3	,	'Laura Adorno'	,	'una dama genovesa'	,	empty_blob()	,	1	,	2	,	5	);
insert into PERSONAJE values(	4	,	'Alvise Badoero'	,	'uno de los líderes de la Inquisición, esposo de Laura'	,	empty_blob()	,	1	,	6	,	5	);
insert into PERSONAJE values(	5	,	'Enzo Grimaldo'	,	'un príncipe genovés, disfrazado como un marino dálmata'	,	empty_blob()	,	1	,	13	,	5	);
insert into PERSONAJE values(	6	,	'Barnaba'	,	'espía de la Inquisición'	,	empty_blob()	,	1	,	5	,	5	);
insert into PERSONAJE values(	7	,	'Zuàne'	,	'un botero compitiendo en la regata'	,	empty_blob()	,	1	,	6	,	5	);
insert into PERSONAJE values(	8	,	'Isépo'	,	'Un escriba'	,	empty_blob()	,	1	,	4	,	5	);
insert into PERSONAJE values(	9	,	'Otelo'	,	'moro, general de la armada veneciana'	,	empty_blob()	,	1	,	14	,	6	);
insert into PERSONAJE values(	10	,	'Desdémona'	,	'Esposa de otelo'	,	empty_blob()	,	1	,	8	,	6	);
insert into PERSONAJE values(	11	,	'Yago'	,	'alférez de Otelo'	,	empty_blob()	,	1	,	16	,	6	);
insert into PERSONAJE values(	12	,	'Emilia'	,	'Esposa de Yago'	,	empty_blob()	,	1	,	2	,	6	);
insert into PERSONAJE values(	13	,	'Lodovico'	,	'embajador de Venecia'	,	empty_blob()	,	1	,	6	,	6	);
insert into PERSONAJE values(	14	,	'Heraldo'	,	null	,	empty_blob()	,	1	,	6	,	6	);
insert into PERSONAJE values(	15	,	'Cassio'	,	'capitán de la armada'	,	empty_blob()	,	1	,	13	,	6	);
insert into PERSONAJE values(	16	,	'Roderigo'	,	'caballero veneciano'	,	empty_blob()	,	1	,	13	,	6	);
insert into PERSONAJE values(	17	,	'Montano'	,	'predecesor de Otelo en el gobierno de Chipre'	,	empty_blob()	,	1	,	6	,	6	);
insert into PERSONAJE values(	18	,	'Conde Almaviva'	,	'noble español libertino'	,	empty_blob()	,	1	,	5	,	8	);
insert into PERSONAJE values(	19	,	'Fígaro'	,	'Sirviente del Conde Almaviva'	,	empty_blob()	,	1	,	5	,	8	);
insert into PERSONAJE values(	20	,	'Cherubino'	,	'paje de la condesa'	,	empty_blob()	,	1	,	2	,	8	);
insert into PERSONAJE values(	21	,	'Don Bartolo'	,	'médico y abogado'	,	empty_blob()	,	1	,	19	,	8	);
insert into PERSONAJE values(	22	,	'Antonio'	,	'jardinero'	,	empty_blob()	,	1	,	12	,	8	);
insert into PERSONAJE values(	23	,	'Curzio'	,	'juez'	,	empty_blob()	,	1	,	4	,	8	);
insert into PERSONAJE values(	24	,	'Condesa Rosinna de Almaviva'	,	'Esposa del conde'	,	empty_blob()	,	1	,	8	,	8	);
insert into PERSONAJE values(	25	,	'Susana'	,	'doncella de la Condesa y prometida de Fígaro'	,	empty_blob()	,	1	,	2	,	8	);
insert into PERSONAJE values(	26	,	'Marcelina'	,	'criada de la Condesa'	,	empty_blob()	,	1	,	2	,	8	);
insert into PERSONAJE values(	27	,	'Barbarina'	,	'sobrina de Antonio'	,	empty_blob()	,	1	,	2	,	8	);
insert into PERSONAJE values(	28	,	'Don Basilio'	,	'profesor de música'	,	empty_blob()	,	1	,	12	,	8	);
insert into PERSONAJE values(	29	,	'Canio'	,	'jefe de los actores'	,	empty_blob()	,	1	,	14	,	7	);
insert into PERSONAJE values(	30	,	'Tonio'	,	'payaso enamorado de Nedda'	,	empty_blob()	,	1	,	5	,	7	);
insert into PERSONAJE values(	31	,	'Peppe'	,	'actor'	,	empty_blob()	,	1	,	12	,	7	);
insert into PERSONAJE values(	32	,	'Nedda'	,	'actriz y esposa de Canio'	,	empty_blob()	,	1	,	8	,	7	);
insert into PERSONAJE values(	33	,	'Silvio'	,	'campesino amante de Nedda'	,	empty_blob()	,	1	,	16	,	7	);
insert into PERSONAJE values(	34	,	'rodolfo'	,	'poeta'	,	empty_blob()	,	1	,	13	,	4	);
insert into PERSONAJE values(	35	,	'mimi'	,	'modistilla'	,	empty_blob()	,	1	,	8	,	4	);
insert into PERSONAJE values(	36	,	'marcello'	,	'pintor'	,	empty_blob()	,	1	,	5	,	4	);
insert into PERSONAJE values(	37	,	'musetta'	,	'coqueta'	,	empty_blob()	,	1	,	7	,	4	);
insert into PERSONAJE values(	38	,	'schaunard'	,	'musico'	,	empty_blob()	,	1	,	17	,	4	);
insert into PERSONAJE values(	39	,	'colline'	,	'filosofo'	,	empty_blob()	,	1	,	6	,	4	);
insert into PERSONAJE values(	40	,	'benoit'	,	'casero'	,	empty_blob()	,	1	,	6	,	4	);
insert into PERSONAJE values(	41	,	'alcindoro'	,	'politico'	,	empty_blob()	,	1	,	6	,	4	);
insert into PERSONAJE values(	42	,	'parpignol'	,	'vendedor de juguete'	,	empty_blob()	,	1	,	4	,	4	);
insert into PERSONAJE values(	43	,	'Adina'	,	'Rica aldeana'	,	empty_blob()	,	1	,	1	,	1	);
insert into PERSONAJE values(	44	,	'Nemorino'	,	'Enamorado de adina'	,	empty_blob()	,	1	,	4	,	1	);
insert into PERSONAJE values(	45	,	'Belcore'	,	'sargento'	,	empty_blob()	,	1	,	5	,	1	);
insert into PERSONAJE values(	46	,	'Dulcamara'	,	'Médico ambulante'	,	empty_blob()	,	1	,	6	,	1	);
insert into PERSONAJE values(	47	,	'Giannetta'	,	'Aldeana'	,	empty_blob()	,	1	,	1	,	1	);