insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'arpa'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'bombo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'chelo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'clarinete'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'clarinete bajo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'clavecin'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'contrabajo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'contrafagot'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'corno'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'corno ingles'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'fagot'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'flauta'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'flautin'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'guitarra'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'obo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'organo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'piano'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'plato'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'timbal'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'triangulo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'trompa'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'trompeta'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'trombon'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'tuba'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'violin'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'violonchelo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'bajo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'trombon bajo'	);
insert into INSTRUMENTO values (	seqInstrumento.nextval	,	'contrabajo trombon'	);