insert into PARTE values(	105	,	'I'	,	'acto'	,	null	,	1	);
insert into PARTE values(	106	,	'Bel conforto al mietitore'	,	'obertura'	,	105	,	1	);
insert into PARTE values(	107	,	'Quanto è bella, quanto è cara'	,	'cavatina'	,	106	,	1	);
insert into PARTE values(	108	,	'Benedette queste carte... Della crudele Isotta '	,	'cavatina'	,	107	,	1	);
insert into PARTE values(	109	,	'Come Paride vezzoso '	,	'cavatina'	,	108	,	1	);
insert into PARTE values(	110	,	'Intanto, o mia ragazza '	,	'recitativo'	,	109	,	1	);
insert into PARTE values(	111	,	'Una parola o Adina... Chiedi all aura lusinghiera'	,	'duo'	,	110	,	1	);
insert into PARTE values(	112	,	'Che vuol dire codesta sonata?'	,	'coro'	,	111	,	1	);
insert into PARTE values(	113	,	'Udite, udite, o rustici'	,	'cavatina'	,	112	,	1	);
insert into PARTE values(	114	,	'Ardir! Ha forse il cielo mandato... Voglio dire, lo stupendo elisir '	,	'recitativo'	,	113	,	1	);
insert into PARTE values(	115	,	'Caro elisir! sei mio! '	,	'recitativo'	,	114	,	1	);
insert into PARTE values(	116	,	'Lallarallara... Esulti pur la barbara'	,	'duo'	,	115	,	1	);
insert into PARTE values(	117	,	'ran, tran, tra. In guerra ed in amor'	,	'trio'	,	116	,	1	);
insert into PARTE values(	118	,	'Signor sargente, di voi richiede la vostra gente... Adina credimi '	,	'cuarteto'	,	117	,	1	);
insert into PARTE values(	119	,	'II'	,	'acto'	,	118	,	1	);
insert into PARTE values(	120	,	'Cantiamo, facciam brindisi '	,	'coro'	,	119	,	1	);
insert into PARTE values(	121	,	'Poiché cantar vi alletta'	,	'recitativo'	,	120	,	1	);
insert into PARTE values(	122	,	'Io son ricco e tu sei bella'	,	'barcarola'	,	121	,	1	);
insert into PARTE values(	123	,	'Silenzio! È qua il notaro'	,	'recitativo'	,	122	,	1	);
insert into PARTE values(	124	,	'Le feste nuziali'	,	'recitativo'	,	123	,	1	);
insert into PARTE values(	125	,	'La donna è un animale stravagante... Venti scudi'	,	'duo'	,	124	,	1	);
insert into PARTE values(	126	,	'Saria possibile'	,	'coro'	,	125	,	1	);
insert into PARTE values(	127	,	'Dell elisir mirabile'	,	'cuarteto'	,	126	,	1	);
insert into PARTE values(	128	,	'Come sen va contento... Quanto amore'	,	'duo'	,	127	,	1	);
insert into PARTE values(	129	,	'Una furtiva lagrima'	,	'romanza'	,	128	,	1	);
insert into PARTE values(	130	,	'Eccola. Oh! qual le accresce beltà'	,	'recitativo'	,	129	,	1	);
insert into PARTE values(	131	,	'Prendi, per me sei libero '	,	'aria'	,	130	,	1	);
insert into PARTE values(	132	,	'Alto! Fronte! '	,	'recitativo'	,	131	,	1	);
insert into PARTE values(	133	,	'Ei corregge ogni difetto'	,	'aria'	,	132	,	1	);