insert into ORQUESTA values (	seqOrquesta.nextval	,	'scpo'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'metropolitan opera'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta sinfonica de atlanta'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	' real academia de bellas artes de san fernando'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'tonhalle'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta de filadelfia'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta de camara de lausana'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'konzerthausorchester berlin'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta sinfonica de la radio sueca'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta real del concertgebouw'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'sinf—nica de pittsburgh'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta filarmonica de oslo'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'deutsche kammerphilharmonie bremen'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta de la age of enlightenment'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta filarmonica de roterdam'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta sinfonica de baltimore'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orchestra sinfonica nazionale della rai'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'rundfunk-sinfonieorchester '	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta filarmonica de brooklyn'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta de paris'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta sinfonica de chicago'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'staatskapelle dresden'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'teatro de la monnaie'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta de la academia nacional de santa cecilia'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta de la radio de munich'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta filarmonica de londres'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'orquesta sinfonica de la radio de baviera'	,	1	);
insert into ORQUESTA values (	seqOrquesta.nextval	,	'royal scottish national orchestra'	,	1	);