insert into LUGAR values (	seqLugar.nextval	,	'afganistan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'albania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'alemania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'andorra'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'angola'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'antigua y barbuda'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'arabia saudita'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'argelia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'argentina'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'armenia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'australia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'austria'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'azerbaijan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bahamas'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bahrein'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bangledesh'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'banin'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'barbados'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'belgica'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'belice'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bhutan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bielorrusia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bolivia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bosnia-herzegovina'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bottswana'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'brasil'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'brunei'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'bulgaria'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'cabo verde'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'camboya'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'chile'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'china'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'chipre'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'colombia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'comores'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'corea del norte'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'corea del sur'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'costa de marfil'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'costa rica'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'croacia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'cuba'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'dinamarca'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'djibuti'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'dominica'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'ecuador'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'egipto'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'el salvador'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'emiratos arabes unidos'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'eritrea'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'eslovaquia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'eslovenia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'espana'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'estados unidos'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'estonia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'etiopia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'fidji'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'filipinas'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'finlandia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'francia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'gabon'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'gambia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'georgia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'ghana'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'gran bretana'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'granada'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'grecia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'guatemala'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'guinea'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'guinea ecuatorial'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'guinea-bissau'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'guyana'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'haiti'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'honduras'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'hungria'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'india'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'indonesia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'inglaterra'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'iran'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'iraq'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'irlanda'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'islandia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'islas marshall'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'islas salomon'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'israel'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'italia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'jamaica'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'japon'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'jordania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'kazajstan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'kenya'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'kirguisistan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'kiribati'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'kuwait'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'laos'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'lesotho'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'letonia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'libano'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'madagascar'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'malasia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'malawi'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'maldivas'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'mali'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'malta'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'marruecos'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'mauricio'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'mauritania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'mexico'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'micronesia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'moldavia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'monaco'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'mongolia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'mozambique'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'myanmar'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'namibia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'nauru'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'nepal'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'nicaragua'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'niger'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'nigeria'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'noruega'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'nueva zelanda'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'oman'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'paises bajos'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'pakistan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'palau'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'panama'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'papua nueva guinea'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'paraguay'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'peru'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'polonia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'portugal'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'qatar'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'republica del congo'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'republica democratica del congo'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'republica dominicana'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'ruanda'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'rumania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'rusia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'saint kitts y nevis'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'samoa'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'san marino'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'santa lucia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'santo tome y principe'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'senegal'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'serbia y montenegro'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'seychelles'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'sierra leona'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'singapur'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'siria'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'somalia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'sri lanka'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'sudafrica'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'sudan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'suecia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'suiza'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'surinam'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'swazilandia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'tadjiskistan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'tailandia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'taiwan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'tanzania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'timor oriental'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'togo'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'tonga'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'trinidad y tobago'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'tunez'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'turkmenistan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'turquia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'tuvali'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'ucrania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'uganda'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'uruguay'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'uzbekistan'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'vanuatu'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'vaticano'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'venezuela'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'vietnam'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'yemen'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'zambia'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'zimbabwe'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'canada'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'gales'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'holanda'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'lituania'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'puerto rico'	,	'p'	,	null	,	null	);
insert into LUGAR values (	seqLugar.nextval	,	'gran londres'	,	'e'	,	null	,	77	);
insert into LUGAR values (	seqLugar.nextval	,	'londres'	,	'c'	,	null	,	186	);
insert into LUGAR values (	seqLugar.nextval	,	'merseyside'	,	'e'	,	null	,	77	);
insert into LUGAR values (	seqLugar.nextval	,	'liverpool'	,	'c'	,	null	,	188	);
insert into LUGAR values (	seqLugar.nextval	,	'gran manchester'	,	'e'	,	null	,	77	);
insert into LUGAR values (	seqLugar.nextval	,	'manchester'	,	'c'	,	null	,	190	);
insert into LUGAR values (	seqLugar.nextval	,	'oxfordshire'	,	'e'	,	null	,	77	);
insert into LUGAR values (	seqLugar.nextval	,	'oxford'	,	'c'	,	null	,	192	);
insert into LUGAR values (	seqLugar.nextval	,	'florida'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'georgia'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'nueva york'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'washington'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'texas'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'miami'	,	'c'	,	null	,	194	);
insert into LUGAR values (	seqLugar.nextval	,	'tampa'	,	'c'	,	null	,	194	);
insert into LUGAR values (	seqLugar.nextval	,	'orlando'	,	'c'	,	null	,	194	);
insert into LUGAR values (	seqLugar.nextval	,	'fort lauderdale'	,	'c'	,	null	,	194	);
insert into LUGAR values (	seqLugar.nextval	,	'atlanta'	,	'c'	,	null	,	195	);
insert into LUGAR values (	seqLugar.nextval	,	'columbus'	,	'c'	,	null	,	195	);
insert into LUGAR values (	seqLugar.nextval	,	'savannah'	,	'c'	,	null	,	195	);
insert into LUGAR values (	seqLugar.nextval	,	'ganesville'	,	'c'	,	null	,	195	);
insert into LUGAR values (	seqLugar.nextval	,	'nueva york'	,	'c'	,	null	,	196	);
insert into LUGAR values (	seqLugar.nextval	,	'seattle'	,	'c'	,	null	,	197	);
insert into LUGAR values (	seqLugar.nextval	,	'houston'	,	'c'	,	null	,	198	);
insert into LUGAR values (	seqLugar.nextval	,	'dallas'	,	'c'	,	null	,	198	);
insert into LUGAR values (	seqLugar.nextval	,	'distrito capital'	,	'e'	,	null	,	176	);
insert into LUGAR values (	seqLugar.nextval	,	'miranda'	,	'e'	,	null	,	176	);
insert into LUGAR values (	seqLugar.nextval	,	'zulia'	,	'e'	,	null	,	176	);
insert into LUGAR values (	seqLugar.nextval	,	'carabobo'	,	'e'	,	null	,	176	);
insert into LUGAR values (	seqLugar.nextval	,	'caracas'	,	'c'	,	null	,	211	);
insert into LUGAR values (	seqLugar.nextval	,	'los teques'	,	'c'	,	null	,	212	);
insert into LUGAR values (	seqLugar.nextval	,	'maracaibo'	,	'c'	,	null	,	213	);
insert into LUGAR values (	seqLugar.nextval	,	'valencia'	,	'c'	,	null	,	214	);
insert into LUGAR values (	seqLugar.nextval	,	'minessota'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'saint paul'	,	'c'	,	null	,	219	);
insert into LUGAR values (	seqLugar.nextval	,	'madrid'	,	'e'	,	null	,	52	);
insert into LUGAR values (	seqLugar.nextval	,	'california'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'san francisco'	,	'c'	,	null	,	222	);
insert into LUGAR values (	seqLugar.nextval	,	'isla de francia'	,	'e'	,	null	,	59	);
insert into LUGAR values (	seqLugar.nextval	,	'rodano-alpes'	,	'e'	,	null	,	59	);
insert into LUGAR values (	seqLugar.nextval	,	'paris'	,	'c'	,	null	,	224	);
insert into LUGAR values (	seqLugar.nextval	,	'lyon'	,	'c'	,	null	,	225	);
insert into LUGAR values (	seqLugar.nextval	,	'reunion '	,	'e'	,	null	,	59	);
insert into LUGAR values (	seqLugar.nextval	,	'saint-denis'	,	'c'	,	null	,	228	);
insert into LUGAR values (	seqLugar.nextval	,	'borgoña'	,	'e'	,	null	,	59	);
insert into LUGAR values (	seqLugar.nextval	,	'dijon'	,	'c'	,	null	,	230	);
insert into LUGAR values (	seqLugar.nextval	,	'lazio'	,	'e'	,	null	,	85	);
insert into LUGAR values (	seqLugar.nextval	,	'roma'	,	'c'	,	null	,	232	);
insert into LUGAR values (	seqLugar.nextval	,	'lombardia'	,	'e'	,	null	,	85	);
insert into LUGAR values (	seqLugar.nextval	,	'milan'	,	'c'	,	null	,	234	);
insert into LUGAR values (	seqLugar.nextval	,	'toscana'	,	'e'	,	null	,	85	);
insert into LUGAR values (	seqLugar.nextval	,	'florencia'	,	'c'	,	null	,	236	);
insert into LUGAR values (	seqLugar.nextval	,	'alameda'	,	'c'	,	null	,	222	);
insert into LUGAR values (	seqLugar.nextval	,	'north rhine-westphalia'	,	'e'	,	null	,	3	);
insert into LUGAR values (	seqLugar.nextval	,	'düsseldorf'	,	'c'	,	null	,	239	);
insert into LUGAR values (	seqLugar.nextval	,	'pensilvania'	,	'e'	,	null	,	53	);
insert into LUGAR values (	seqLugar.nextval	,	'filadelfia'	,	'c'	,	null	,	241	);
insert into LUGAR values (	seqLugar.nextval	,	'romande'	,	'e'	,	null	,	155	);
insert into LUGAR values (	seqLugar.nextval	,	'laussane'	,	'c'	,	null	,	243	);
insert into LUGAR values (	seqLugar.nextval	,	'berlin'	,	'e'	,	null	,	3	);
insert into LUGAR values (	seqLugar.nextval	,	'estocolmo'	,	'e'	,	null	,	154	);
insert into LUGAR values (	seqLugar.nextval	,	'estocolmo'	,	'c'	,	null	,	246	);
insert into LUGAR values (	seqLugar.nextval	,	'septentrional'	,	'e'	,	null	,	183	);
insert into LUGAR values (	seqLugar.nextval	,	'amsterdam'	,	'c'	,	null	,	248	);
insert into LUGAR values (	seqLugar.nextval	,	'republica checa'	,	'p'	,	null	,	null	);