insert into FACTURA_DIGITALIZACION values (	1	, to_date(	'18/1/13'	, 'dd/mm/yy'),	8	);
insert into FACTURA_DIGITALIZACION values (	2	, to_date(	'25/1/13'	, 'dd/mm/yy'),	80	);
insert into FACTURA_DIGITALIZACION values (	3	, to_date(	'23/1/13'	, 'dd/mm/yy'),	144	);
insert into FACTURA_DIGITALIZACION values (	4	, to_date(	'17/1/13'	, 'dd/mm/yy'),	17	);
insert into FACTURA_DIGITALIZACION values (	5	, to_date(	'25/1/13'	, 'dd/mm/yy'),	87	);
insert into FACTURA_DIGITALIZACION values (	6	, to_date(	'22/1/13'	, 'dd/mm/yy'),	131	);
insert into FACTURA_DIGITALIZACION values (	7	, to_date(	'21/1/13'	, 'dd/mm/yy'),	124	);
insert into FACTURA_DIGITALIZACION values (	8	, to_date(	'17/1/13'	, 'dd/mm/yy'),	5	);
insert into FACTURA_DIGITALIZACION values (	9	, to_date(	'18/1/13'	, 'dd/mm/yy'),	58	);
insert into FACTURA_DIGITALIZACION values (	10	, to_date(	'24/1/13'	, 'dd/mm/yy'),	128	);
insert into FACTURA_DIGITALIZACION values (	11	, to_date(	'19/1/13'	, 'dd/mm/yy'),	107	);
insert into FACTURA_DIGITALIZACION values (	12	, to_date(	'18/1/13'	, 'dd/mm/yy'),	19	);
insert into FACTURA_DIGITALIZACION values (	13	, to_date(	'23/1/13'	, 'dd/mm/yy'),	53	);
insert into FACTURA_DIGITALIZACION values (	14	, to_date(	'25/1/13'	, 'dd/mm/yy'),	44	);
insert into FACTURA_DIGITALIZACION values (	15	, to_date(	'19/1/13'	, 'dd/mm/yy'),	21	);
insert into FACTURA_DIGITALIZACION values (	16	, to_date(	'22/1/13'	, 'dd/mm/yy'),	130	);
insert into FACTURA_DIGITALIZACION values (	17	, to_date(	'17/1/13'	, 'dd/mm/yy'),	80	);
insert into FACTURA_DIGITALIZACION values (	18	, to_date(	'19/1/13'	, 'dd/mm/yy'),	116	);
insert into FACTURA_DIGITALIZACION values (	19	, to_date(	'16/1/13'	, 'dd/mm/yy'),	43	);
insert into FACTURA_DIGITALIZACION values (	20	, to_date(	'21/1/13'	, 'dd/mm/yy'),	131	);
insert into FACTURA_DIGITALIZACION values (	21	, to_date(	'16/1/13'	, 'dd/mm/yy'),	142	);
insert into FACTURA_DIGITALIZACION values (	22	, to_date(	'25/1/13'	, 'dd/mm/yy'),	113	);
insert into FACTURA_DIGITALIZACION values (	23	, to_date(	'20/1/13'	, 'dd/mm/yy'),	98	);
insert into FACTURA_DIGITALIZACION values (	24	, to_date(	'22/1/13'	, 'dd/mm/yy'),	84	);
insert into FACTURA_DIGITALIZACION values (	25	, to_date(	'20/1/13'	, 'dd/mm/yy'),	24	);
insert into FACTURA_DIGITALIZACION values (	26	, to_date(	'22/1/13'	, 'dd/mm/yy'),	140	);
insert into FACTURA_DIGITALIZACION values (	27	, to_date(	'24/1/13'	, 'dd/mm/yy'),	39	);
insert into FACTURA_DIGITALIZACION values (	28	, to_date(	'17/1/13'	, 'dd/mm/yy'),	49	);
insert into FACTURA_DIGITALIZACION values (	29	, to_date(	'24/1/13'	, 'dd/mm/yy'),	21	);
insert into FACTURA_DIGITALIZACION values (	30	, to_date(	'20/1/13'	, 'dd/mm/yy'),	21	);
insert into FACTURA_DIGITALIZACION values (	31	, to_date(	'22/1/13'	, 'dd/mm/yy'),	98	);
insert into FACTURA_DIGITALIZACION values (	32	, to_date(	'24/1/13'	, 'dd/mm/yy'),	43	);
insert into FACTURA_DIGITALIZACION values (	33	, to_date(	'20/1/13'	, 'dd/mm/yy'),	20	);
insert into FACTURA_DIGITALIZACION values (	34	, to_date(	'16/1/13'	, 'dd/mm/yy'),	110	);
insert into FACTURA_DIGITALIZACION values (	35	, to_date(	'19/1/13'	, 'dd/mm/yy'),	121	);
insert into FACTURA_DIGITALIZACION values (	36	, to_date(	'21/1/13'	, 'dd/mm/yy'),	87	);
insert into FACTURA_DIGITALIZACION values (	37	, to_date(	'18/1/13'	, 'dd/mm/yy'),	10	);
insert into FACTURA_DIGITALIZACION values (	38	, to_date(	'19/1/13'	, 'dd/mm/yy'),	32	);
insert into FACTURA_DIGITALIZACION values (	39	, to_date(	'17/1/13'	, 'dd/mm/yy'),	57	);
insert into FACTURA_DIGITALIZACION values (	40	, to_date(	'18/1/13'	, 'dd/mm/yy'),	84	);
insert into FACTURA_DIGITALIZACION values (	41	, to_date(	'19/1/13'	, 'dd/mm/yy'),	141	);
insert into FACTURA_DIGITALIZACION values (	42	, to_date(	'18/1/13'	, 'dd/mm/yy'),	52	);
insert into FACTURA_DIGITALIZACION values (	43	, to_date(	'24/1/13'	, 'dd/mm/yy'),	84	);
insert into FACTURA_DIGITALIZACION values (	44	, to_date(	'18/1/13'	, 'dd/mm/yy'),	36	);
insert into FACTURA_DIGITALIZACION values (	45	, to_date(	'19/1/13'	, 'dd/mm/yy'),	13	);
insert into FACTURA_DIGITALIZACION values (	46	, to_date(	'23/1/13'	, 'dd/mm/yy'),	125	);
insert into FACTURA_DIGITALIZACION values (	47	, to_date(	'23/1/13'	, 'dd/mm/yy'),	145	);
insert into FACTURA_DIGITALIZACION values (	48	, to_date(	'18/1/13'	, 'dd/mm/yy'),	40	);
insert into FACTURA_DIGITALIZACION values (	49	, to_date(	'20/1/13'	, 'dd/mm/yy'),	91	);
insert into FACTURA_DIGITALIZACION values (	50	, to_date(	'21/1/13'	, 'dd/mm/yy'),	5	);
insert into FACTURA_DIGITALIZACION values (	51	, to_date(	'19/1/13'	, 'dd/mm/yy'),	55	);
insert into FACTURA_DIGITALIZACION values (	52	, to_date(	'21/1/13'	, 'dd/mm/yy'),	3	);
insert into FACTURA_DIGITALIZACION values (	53	, to_date(	'20/1/13'	, 'dd/mm/yy'),	79	);
insert into FACTURA_DIGITALIZACION values (	54	, to_date(	'24/1/13'	, 'dd/mm/yy'),	25	);
insert into FACTURA_DIGITALIZACION values (	55	, to_date(	'20/1/13'	, 'dd/mm/yy'),	145	);
insert into FACTURA_DIGITALIZACION values (	56	, to_date(	'18/1/13'	, 'dd/mm/yy'),	26	);
insert into FACTURA_DIGITALIZACION values (	57	, to_date(	'21/1/13'	, 'dd/mm/yy'),	86	);
insert into FACTURA_DIGITALIZACION values (	58	, to_date(	'23/1/13'	, 'dd/mm/yy'),	11	);
insert into FACTURA_DIGITALIZACION values (	59	, to_date(	'20/1/13'	, 'dd/mm/yy'),	128	);
insert into FACTURA_DIGITALIZACION values (	60	, to_date(	'16/1/13'	, 'dd/mm/yy'),	97	);
insert into FACTURA_DIGITALIZACION values (	61	, to_date(	'23/1/13'	, 'dd/mm/yy'),	116	);
insert into FACTURA_DIGITALIZACION values (	62	, to_date(	'24/1/13'	, 'dd/mm/yy'),	45	);
insert into FACTURA_DIGITALIZACION values (	63	, to_date(	'20/1/13'	, 'dd/mm/yy'),	141	);
insert into FACTURA_DIGITALIZACION values (	64	, to_date(	'20/1/13'	, 'dd/mm/yy'),	105	);
insert into FACTURA_DIGITALIZACION values (	65	, to_date(	'24/1/13'	, 'dd/mm/yy'),	68	);
insert into FACTURA_DIGITALIZACION values (	66	, to_date(	'18/1/13'	, 'dd/mm/yy'),	89	);
insert into FACTURA_DIGITALIZACION values (	67	, to_date(	'22/1/13'	, 'dd/mm/yy'),	40	);
insert into FACTURA_DIGITALIZACION values (	68	, to_date(	'22/1/13'	, 'dd/mm/yy'),	130	);
insert into FACTURA_DIGITALIZACION values (	69	, to_date(	'24/1/13'	, 'dd/mm/yy'),	131	);
insert into FACTURA_DIGITALIZACION values (	70	, to_date(	'22/1/13'	, 'dd/mm/yy'),	99	);
insert into FACTURA_DIGITALIZACION values (	71	, to_date(	'22/1/13'	, 'dd/mm/yy'),	130	);
insert into FACTURA_DIGITALIZACION values (	72	, to_date(	'23/1/13'	, 'dd/mm/yy'),	30	);
insert into FACTURA_DIGITALIZACION values (	73	, to_date(	'20/1/13'	, 'dd/mm/yy'),	111	);
insert into FACTURA_DIGITALIZACION values (	74	, to_date(	'16/1/13'	, 'dd/mm/yy'),	70	);
insert into FACTURA_DIGITALIZACION values (	75	, to_date(	'24/1/13'	, 'dd/mm/yy'),	13	);
insert into FACTURA_DIGITALIZACION values (	76	, to_date(	'17/1/13'	, 'dd/mm/yy'),	80	);
insert into FACTURA_DIGITALIZACION values (	77	, to_date(	'17/1/13'	, 'dd/mm/yy'),	26	);
insert into FACTURA_DIGITALIZACION values (	78	, to_date(	'17/1/13'	, 'dd/mm/yy'),	108	);
insert into FACTURA_DIGITALIZACION values (	79	, to_date(	'19/1/13'	, 'dd/mm/yy'),	105	);
insert into FACTURA_DIGITALIZACION values (	80	, to_date(	'19/1/13'	, 'dd/mm/yy'),	78	);
insert into FACTURA_DIGITALIZACION values (	81	, to_date(	'18/1/13'	, 'dd/mm/yy'),	95	);
insert into FACTURA_DIGITALIZACION values (	82	, to_date(	'18/1/13'	, 'dd/mm/yy'),	107	);
insert into FACTURA_DIGITALIZACION values (	83	, to_date(	'23/1/13'	, 'dd/mm/yy'),	85	);
insert into FACTURA_DIGITALIZACION values (	84	, to_date(	'21/1/13'	, 'dd/mm/yy'),	61	);
insert into FACTURA_DIGITALIZACION values (	85	, to_date(	'24/1/13'	, 'dd/mm/yy'),	141	);
insert into FACTURA_DIGITALIZACION values (	86	, to_date(	'20/1/13'	, 'dd/mm/yy'),	139	);
insert into FACTURA_DIGITALIZACION values (	87	, to_date(	'16/1/13'	, 'dd/mm/yy'),	18	);
insert into FACTURA_DIGITALIZACION values (	88	, to_date(	'24/1/13'	, 'dd/mm/yy'),	114	);
insert into FACTURA_DIGITALIZACION values (	89	, to_date(	'16/1/13'	, 'dd/mm/yy'),	128	);
insert into FACTURA_DIGITALIZACION values (	90	, to_date(	'17/1/13'	, 'dd/mm/yy'),	114	);
insert into FACTURA_DIGITALIZACION values (	91	, to_date(	'23/1/13'	, 'dd/mm/yy'),	20	);
insert into FACTURA_DIGITALIZACION values (	92	, to_date(	'25/1/13'	, 'dd/mm/yy'),	4	);
insert into FACTURA_DIGITALIZACION values (	93	, to_date(	'22/1/13'	, 'dd/mm/yy'),	2	);
insert into FACTURA_DIGITALIZACION values (	94	, to_date(	'21/1/13'	, 'dd/mm/yy'),	100	);
insert into FACTURA_DIGITALIZACION values (	95	, to_date(	'25/1/13'	, 'dd/mm/yy'),	83	);
insert into FACTURA_DIGITALIZACION values (	96	, to_date(	'23/1/13'	, 'dd/mm/yy'),	19	);
insert into FACTURA_DIGITALIZACION values (	97	, to_date(	'22/1/13'	, 'dd/mm/yy'),	8	);
insert into FACTURA_DIGITALIZACION values (	98	, to_date(	'25/1/13'	, 'dd/mm/yy'),	142	);
insert into FACTURA_DIGITALIZACION values (	99	, to_date(	'21/1/13'	, 'dd/mm/yy'),	44	);
insert into FACTURA_DIGITALIZACION values (	100	, to_date(	'20/1/13'	, 'dd/mm/yy'),	35	);
insert into FACTURA_DIGITALIZACION values (	101	, to_date(	'23/1/13'	, 'dd/mm/yy'),	75	);
insert into FACTURA_DIGITALIZACION values (	102	, to_date(	'16/1/13'	, 'dd/mm/yy'),	37	);
insert into FACTURA_DIGITALIZACION values (	103	, to_date(	'24/1/13'	, 'dd/mm/yy'),	110	);
insert into FACTURA_DIGITALIZACION values (	104	, to_date(	'25/1/13'	, 'dd/mm/yy'),	55	);
insert into FACTURA_DIGITALIZACION values (	105	, to_date(	'19/1/13'	, 'dd/mm/yy'),	84	);
insert into FACTURA_DIGITALIZACION values (	106	, to_date(	'22/1/13'	, 'dd/mm/yy'),	18	);
insert into FACTURA_DIGITALIZACION values (	107	, to_date(	'24/1/13'	, 'dd/mm/yy'),	89	);
insert into FACTURA_DIGITALIZACION values (	108	, to_date(	'17/1/13'	, 'dd/mm/yy'),	139	);
insert into FACTURA_DIGITALIZACION values (	109	, to_date(	'16/1/13'	, 'dd/mm/yy'),	146	);
insert into FACTURA_DIGITALIZACION values (	110	, to_date(	'20/1/13'	, 'dd/mm/yy'),	43	);
insert into FACTURA_DIGITALIZACION values (	111	, to_date(	'16/1/13'	, 'dd/mm/yy'),	46	);
insert into FACTURA_DIGITALIZACION values (	112	, to_date(	'21/1/13'	, 'dd/mm/yy'),	84	);
insert into FACTURA_DIGITALIZACION values (	113	, to_date(	'24/1/13'	, 'dd/mm/yy'),	47	);
insert into FACTURA_DIGITALIZACION values (	114	, to_date(	'19/1/13'	, 'dd/mm/yy'),	22	);
insert into FACTURA_DIGITALIZACION values (	115	, to_date(	'19/1/13'	, 'dd/mm/yy'),	144	);
insert into FACTURA_DIGITALIZACION values (	116	, to_date(	'22/1/13'	, 'dd/mm/yy'),	111	);
insert into FACTURA_DIGITALIZACION values (	117	, to_date(	'24/1/13'	, 'dd/mm/yy'),	132	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	1	,	2	,	146	,	1	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	2	,	7	,	146	,	2	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	3	,	10	,	146	,	3	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	4	,	2	,	146	,	4	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	5	,	8	,	146	,	5	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	6	,	9	,	146	,	6	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	7	,	4	,	146	,	7	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	8	,	3	,	146	,	8	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	9	,	3	,	146	,	9	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	10	,	6	,	146	,	10	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	11	,	3	,	146	,	11	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	12	,	3	,	146	,	12	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	13	,	3	,	146	,	13	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	14	,	4	,	146	,	14	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	15	,	2	,	146	,	15	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	16	,	10	,	146	,	16	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	17	,	3	,	146	,	17	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	18	,	8	,	146	,	18	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	19	,	4	,	146	,	19	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	20	,	6	,	146	,	20	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	21	,	5	,	146	,	21	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	22	,	4	,	146	,	22	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	23	,	6	,	146	,	23	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	24	,	8	,	146	,	24	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	25	,	7	,	146	,	25	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	26	,	5	,	146	,	26	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	27	,	2	,	146	,	27	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	28	,	9	,	146	,	28	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	29	,	10	,	119	,	29	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	30	,	3	,	119	,	30	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	31	,	7	,	119	,	31	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	32	,	8	,	119	,	32	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	33	,	7	,	119	,	33	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	34	,	1	,	119	,	34	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	35	,	2	,	119	,	35	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	36	,	8	,	119	,	36	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	37	,	8	,	119	,	37	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	38	,	6	,	119	,	38	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	39	,	2	,	119	,	39	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	40	,	1	,	119	,	40	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	41	,	9	,	119	,	41	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	42	,	1	,	119	,	42	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	43	,	8	,	119	,	43	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	44	,	6	,	119	,	44	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	45	,	7	,	119	,	45	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	46	,	5	,	119	,	46	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	47	,	6	,	119	,	47	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	48	,	2	,	119	,	48	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	49	,	3	,	119	,	49	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	50	,	5	,	119	,	50	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	51	,	2	,	119	,	51	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	52	,	6	,	119	,	52	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	53	,	10	,	119	,	53	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	54	,	5	,	119	,	54	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	55	,	6	,	119	,	55	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	56	,	4	,	119	,	56	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	57	,	4	,	119	,	57	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	58	,	9	,	119	,	58	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	59	,	6	,	119	,	59	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	60	,	9	,	119	,	60	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	61	,	8	,	119	,	61	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	62	,	9	,	119	,	62	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	63	,	4	,	119	,	63	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	64	,	4	,	119	,	64	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	65	,	10	,	119	,	65	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	66	,	4	,	119	,	66	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	67	,	4	,	119	,	67	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	68	,	9	,	119	,	68	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	69	,	5	,	119	,	69	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	70	,	3	,	119	,	70	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	71	,	8	,	119	,	71	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	72	,	3	,	119	,	72	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	73	,	9	,	119	,	73	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	74	,	5	,	119	,	74	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	75	,	4	,	119	,	75	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	76	,	1	,	119	,	76	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	77	,	8	,	119	,	77	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	78	,	3	,	146	,	78	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	79	,	2	,	146	,	79	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	80	,	6	,	146	,	80	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	81	,	6	,	146	,	81	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	82	,	7	,	146	,	82	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	83	,	9	,	151	,	83	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	84	,	8	,	151	,	84	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	85	,	2	,	83	,	85	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	86	,	3	,	146	,	86	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	87	,	2	,	146	,	87	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	88	,	3	,	146	,	88	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	89	,	8	,	146	,	89	,	18	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	90	,	6	,	146	,	90	,	16	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	91	,	6	,	83	,	91	,		,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	92	,	6	,	151	,	92	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	93	,	3	,	151	,	93	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	94	,	5	,	151	,	94	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	95	,	10	,	151	,	95	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	96	,	1	,	83	,	96	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	97	,	9	,	83	,	97	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	98	,	6	,	83	,	98	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	99	,	5	,	83	,	99	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	100	,	10	,	119	,	100	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	101	,	5	,	151	,	101	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	102	,	10	,	119	,	102	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	103	,	9	,	151	,	103	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	104	,	5	,	151	,	104	,	10	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	105	,	7	,	119	,	105	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	106	,	4	,	151	,	106	,	10	,		);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	107	,	2	,	151	,	107	,	10	,		);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	108	,	8	,	119	,	108	,	null	,	18	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	109	,	9	,	119	,	109	,	null	,	16	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	110	,	7	,	119	,	110	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	111	,	5	,	119	,	111	,	null	,	17	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	112	,	6	,	83	,	112	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	113	,	6	,	83	,	113	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	114	,	6	,	146	,	114	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	115	,	3	,	146	,	115	,	17	,	null	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	116	,	1	,	83	,	116	,	null	,	10	);
insert into DETALLE_FACTURA_DIGITALIZADA (idDFD, cantidad, monto, fkfd, fkvideo, fkaudio) values(	117	,	5	,	83	,	117	,	null	,	10	);