insert into PARTE values(	1	,	'I'	,	'acto'	,	null	,	8	);
insert into PARTE values(	2	,	're mayor'	,	'obertura'	,	1	,	8	);
insert into PARTE values(	3	,	'Cinque... dieci.... venti...'	,	'duo'	,	2	,	8	);
insert into PARTE values(	4	,	'Se a caso madama la notte ti chiama'	,	'duo'	,	3	,	8	);
insert into PARTE values(	5	,	'Se a caso madama la notte ti chiama'	,	'recitativo'	,	4	,	8	);
insert into PARTE values(	6	,	'Se vuol ballare'	,	'cavatina'	,	5	,	8	);
insert into PARTE values(	7	,	'La vendetta'	,	'aria'	,	6	,	8	);
insert into PARTE values(	8	,	'Via resti servita'	,	'duo'	,	7	,	8	);
insert into PARTE values(	9	,	'Non so più cosa son, cosa faccio'	,	'aria'	,	8	,	8	);
insert into PARTE values(	10	,	'Cosa sento!'	,	'trio'	,	9	,	8	);
insert into PARTE values(	11	,	'Non più andrai'	,	'aria'	,	10	,	8	);
insert into PARTE values(	12	,	'Giovani liete'	,	'coro'	,	11	,	8	);
insert into PARTE values(	13	,	'II'	,	'acto'	,	12	,	8	);
insert into PARTE values(	14	,	'Porgi, amor, qualche ristoro'	,	'cavatina'	,	13	,	8	);
insert into PARTE values(	15	,	'Voi che sapete che cosa è amor'	,	'aria'	,	14	,	8	);
insert into PARTE values(	16	,	'Venite, inginocchiatevi'	,	'aria'	,	15	,	8	);
insert into PARTE values(	17	,	'Esci ormai'	,	'concertante'	,	16	,	8	);
insert into PARTE values(	18	,	'III'	,	'acto'	,	17	,	8	);
insert into PARTE values(	19	,	'Riconosci in quest amplesso'	,	'concertante'	,	18	,	8	);
insert into PARTE values(	20	,	'Crudel! Perché finora,'	,	'duo'	,	19	,	8	);
insert into PARTE values(	21	,	'Hai giá vinta la causa...Vedró, mentrio sospiro'	,	'recitativo'	,	20	,	8	);
insert into PARTE values(	22	,	'Hai giá vinta la causa...Vedró, mentrio sospiro'	,	'aria'	,	21	,	8	);
insert into PARTE values(	23	,	'Che soave zeffiretto'	,	'duo'	,	22	,	8	);
insert into PARTE values(	24	,	'E Susanna non vien!...Dove sono i bei momenti'	,	'recitativo'	,	23	,	8	);
insert into PARTE values(	25	,	'IV'	,	'acto'	,	24	,	8	);