insert into CARGO values (	seqCargo.nextval	,	'presidente'	,	'nombrado'	,	5	,	null	);
insert into CARGO values (	seqCargo.nextval	,	'vicepresidente'	,	'nombrado'	,	5	,	1	);
insert into CARGO values (	seqCargo.nextval	,	'gerente general'	,	'tiempo'	,	5	,	2	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de ventas'	,	'tiempo'	,	1	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de ventas'	,	'tiempo'	,	1	,	4	);
insert into CARGO values (	seqCargo.nextval	,	'taquillero'	,	'tiempo'	,	1	,	5	);
insert into CARGO values (	seqCargo.nextval	,	'promotor'	,	'tiempo'	,	1	,	5	);
insert into CARGO values (	seqCargo.nextval	,	'publicista'	,	'tiempo'	,	1	,	5	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de finanzas'	,	'tiempo'	,	2	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de finanzas'	,	'tiempo'	,	2	,	9	);
insert into CARGO values (	seqCargo.nextval	,	'contador'	,	'tiempo'	,	2	,	10	);
insert into CARGO values (	seqCargo.nextval	,	'administrador'	,	'tiempo'	,	2	,	10	);
insert into CARGO values (	seqCargo.nextval	,	'auditor'	,	'tiempo'	,	2	,	10	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de limpieza'	,	'tiempo'	,	4	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de limpieza'	,	'tiempo'	,	4	,	14	);
insert into CARGO values (	seqCargo.nextval	,	'aseador'	,	'tiempo'	,	4	,	15	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de recursos humanos'	,	'tiempo'	,	3	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de recursos humanos'	,	'tiempo'	,	3	,	17	);
insert into CARGO values (	seqCargo.nextval	,	'administrador de reclutamiento'	,	'tiempo'	,	3	,	18	);
insert into CARGO values (	seqCargo.nextval	,	'administrador de seleccion'	,	'tiempo'	,	3	,	18	);
insert into CARGO values (	seqCargo.nextval	,	'administrador de capacitacion'	,	'tiempo'	,	3	,	18	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de produccion'	,	'tiempo'	,	6	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de produccion'	,	'tiempo'	,	6	,	22	);
insert into CARGO values (	seqCargo.nextval	,	'director'	,	'nombrado'	,	6	,	23	);
insert into CARGO values (	seqCargo.nextval	,	'director de escenografia'	,	'nombrado'	,	6	,	23	);
insert into CARGO values (	seqCargo.nextval	,	'autor'	,	'nombrado'	,	6	,	23	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de sonido'	,	'nombrado'	,	7	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de sonido'	,	'tiempo'	,	7	,	27	);
insert into CARGO values (	seqCargo.nextval	,	'ingeniero en sonido'	,	'tiempo'	,	7	,	28	);
insert into CARGO values (	seqCargo.nextval	,	'supervisor de equipos'	,	'tiempo'	,	7	,	28	);
insert into CARGO values (	seqCargo.nextval	,	'tecnico en sonido'	,	'tiempo'	,	7	,	28	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de canto'	,	'nombrado'	,	9	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de canto'	,	'tiempo'	,	9	,	31	);
insert into CARGO values (	seqCargo.nextval	,	'cantante'	,	'nombrado'	,	9	,	32	);
insert into CARGO values (	seqCargo.nextval	,	'entrenador vocal'	,	'tiempo'	,	9	,	32	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de musica'	,	'nombrado'	,	10	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de musica'	,	'tiempo'	,	10	,	36	);
insert into CARGO values (	seqCargo.nextval	,	'musico'	,	'nombrado'	,	10	,	37	);
insert into CARGO values (	seqCargo.nextval	,	'entrenador musical'	,	'tiempo'	,	10	,	37	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de baile'	,	'nombrado'	,	11	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de baile'	,	'tiempo'	,	11	,	39	);
insert into CARGO values (	seqCargo.nextval	,	'coreografo'	,	'nombrado'	,	11	,	38	);
insert into CARGO values (	seqCargo.nextval	,	'bailarin'	,	'nombrado'	,	11	,	38	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador de iluminacion'	,	'nombrado'	,	8	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente de iluminacion'	,	'tiempo'	,	8	,	44	);
insert into CARGO values (	seqCargo.nextval	,	'disenador de iluminacion'	,	'tiempo'	,	8	,	45	);
insert into CARGO values (	seqCargo.nextval	,	'tecnico en iluminacion'	,	'tiempo'	,	8	,	45	);
insert into CARGO values (	seqCargo.nextval	,	'coordinador tecnologico'	,	'nombrado'	,	12	,	3	);
insert into CARGO values (	seqCargo.nextval	,	'gerente tecnologico'	,	'tiempo'	,	12	,	48	);
insert into CARGO values (	seqCargo.nextval	,	'administrador de base de datos'	,	'nombrado'	,	12	,	49	);
insert into CARGO values (	seqCargo.nextval	,	'administrador de redes'	,	'nombrado'	,	12	,	49	);
insert into CARGO values (	seqCargo.nextval	,	'administrador web'	,	'nombrado'	,	12	,	49	);
insert into CARGO values (	seqCargo.nextval	,	'tecnico'	,	'nombrado'	,	12	,	49	);
insert into CARGO values (	seqCargo.nextval	,	'director musical'	,	'nombrado'	,	10	,	36	);
insert into CARGO values (	seqCargo.nextval	,	'escenografo'	,	'nombrado'	,	6	,	25	);