insert into PARTE values(	26	,	'L ho perduta, me meschina '	,	'cavatina'	,	25	,	8	);
insert into PARTE values(	27	,	'il capro e la capretta'	,	'aria'	,	26	,	8	);
insert into PARTE values(	28	,	'Deh viene, non tardar'	,	'aria'	,	27	,	8	);
insert into PARTE values(	29	,	'Tutto e disposto…Aprite un po quegli occhi'	,	'recitativo'	,	28	,	8	);
insert into PARTE values(	30	,	'Giunse alfin il momento… Deh vieni, non tardar'	,	'recitativo'	,	29	,	8	);
insert into PARTE values(	31	,	'In quegli anni'	,	'aria'	,	30	,	8	);
insert into PARTE values(	32	,	'I'	,	'acto'	,	null	,	5	);
insert into PARTE values(	33	,	'Voce di donna o d angelo'	,	'aria'	,	32	,	5	);
insert into PARTE values(	34	,	'O monumento'	,	'aria'	,	33	,	5	);
insert into PARTE values(	35	,	'II'	,	'acto'	,	34	,	5	);
insert into PARTE values(	36	,	'Ah, pescator affonda lesca'	,	'barcarola'	,	35	,	5	);
insert into PARTE values(	37	,	'Cielo e mar!'	,	'aria'	,	36	,	5	);
insert into PARTE values(	38	,	'Stella del marinar!'	,	'aria'	,	37	,	5	);
insert into PARTE values(	39	,	'III'	,	'acto'	,	38	,	5	);
insert into PARTE values(	40	,	'Si, morir ella de!'	,	'aria'	,	39	,	5	);
insert into PARTE values(	41	,	'IV'	,	'aria'	,	40	,	5	);
insert into PARTE values(	42	,	'Suicidio'	,	'aria'	,	41	,	5	);
insert into PARTE values(	44	,	'I'	,	'acto'	,	null	,	6	);
insert into PARTE values(	45	,	'¡Una vela!'	,	'coro'	,	44	,	6	);
insert into PARTE values(	46	,	'Esultate! L orgoglio musulmano sepolto è in mar'	,	'coro'	,	45	,	6	);
insert into PARTE values(	47	,	'Roderigo, ebben che pensi?'	,	'duo'	,	46	,	6	);
insert into PARTE values(	48	,	'Fuoco di gioia'	,	'coro'	,	47	,	6	);
insert into PARTE values(	49	,	'Roderigo, beviam'	,	'trio'	,	48	,	6	);
insert into PARTE values(	50	,	'inaffia l ugola'	,	'trio'	,	49	,	6	);
insert into PARTE values(	51	,	'capitano, v attende la fazione ai baluardi'	,	'cuarteto'	,	50	,	6	);
insert into PARTE values(	52	,	'Abbasso le spade'	,	'cuarteto'	,	51	,	6	);
insert into PARTE values(	53	,	'Gia nella notte densa s estingue ogni clamor'	,	'duo'	,	52	,	6	);
insert into PARTE values(	54	,	'II'	,	'acto'	,	53	,	6	);
insert into PARTE values(	55	,	'Non ti crucciar'	,	'duo'	,	54	,	6	);
insert into PARTE values(	56	,	'Credo in un Dio crudel'	,	'aria'	,	55	,	6	);
insert into PARTE values(	57	,	'Cio maccora…Che parli'	,	'duo'	,	56	,	6	);
insert into PARTE values(	58	,	'Dove guardi splendono raggi'	,	'coro'	,	57	,	6	);
insert into PARTE values(	59	,	'D un uom che geme sotto il tuo disdegno la preghiera ti porto'	,	'duo'	,	58	,	6	);
insert into PARTE values(	60	,	'Ora e per sempre addio sante memorie'	,	'aria'	,	59	,	6	);
insert into PARTE values(	61	,	'Era la notte'	,	'aria'	,	60	,	6	);
insert into PARTE values(	62	,	'Si, pel ciel marmoreo giuro'	,	'duo'	,	61	,	6	);
insert into PARTE values(	63	,	'III'	,	'acto'	,	62	,	6	);
insert into PARTE values(	64	,	'Qui trarro cassio'	,	'aria'	,	63	,	6	);
insert into PARTE values(	65	,	'Dio ti giocondi, o sposo'	,	'duo'	,	64	,	6	);
insert into PARTE values(	66	,	'Dio ! Mi potevi scagliar tutti i mali'	,	'aria'	,	65	,	6	);
insert into PARTE values(	67	,	'Esterrefatta fisso lo sguardo tuo tremendo'	,	'duo'	,	66	,	6	);