insert into PARTE values(	68	,	'vieni; l aula e deserta'	,	'trio'	,	67	,	6	);
insert into PARTE values(	69	,	'Questa e una ragna dove il tuo cuor casca'	,	'aria'	,	68	,	6	);
insert into PARTE values(	70	,	'Il doge ed il Senato salutano l eroe trionfatore'	,	'coro'	,	69	,	6	);
insert into PARTE values(	71	,	'fuggite!'	,	'coro'	,	70	,	6	);
insert into PARTE values(	72	,	'IV'	,	'acto'	,	71	,	6	);
insert into PARTE values(	73	,	'Piangea cantando nell erma landa'	,	'aria'	,	72	,	6	);
insert into PARTE values(	74	,	'Diceste questa sera le vostre preci'	,	'duo'	,	73	,	6	);
insert into PARTE values(	75	,	'aprite! Aprite!'	,	'coro'	,	74	,	6	);
insert into PARTE values(	76	,	'Niun mi tema'	,	'cuarteto'	,	75	,	6	);
insert into PARTE values(	77	,	'I'	,	'acto'	,	null	,	7	);
insert into PARTE values(	78	,	'Si può?'	,	'obertura'	,	78	,	7	);
insert into PARTE values(	79	,	'Son qua, ritornano!'	,	'coro'	,	79	,	7	);
insert into PARTE values(	80	,	'Qual fiamma avea nel guardo'	,	'aria'	,	80	,	7	);
insert into PARTE values(	81	,	'Un tal gioco, credete mi'	,	'aria'	,	81	,	7	);
insert into PARTE values(	82	,	'Stridono lassù'	,	'aria'	,	82	,	7	);
insert into PARTE values(	83	,	'Vesti la giubba'	,	'aria'	,	83	,	7	);
insert into PARTE values(	84	,	'II'	,	'acto'	,	84	,	7	);
insert into PARTE values(	85	,	'Canzone di Arlecchino'	,	'aria'	,	85	,	7	);
insert into PARTE values(	86	,	'No, pagliaccio non son'	,	'aria'	,	86	,	7	);
insert into PARTE values(	87	,	'O Columbina, il tenero fido Arlecchin'	,	'aria'	,	87	,	7	);